gddemo:  gddemo.cpp GridDisplay.o
	g++ -o gddemo gddemo.cpp GridDisplay.o

gddemo: gddemo.cpp GridDisplay.o
	g++ -o gddemo gddemo.cpp GridDisplay.o

GridDisplay.o: GridDisplay.cpp GridDisplay.h
	g++ -c GridDisplay.cpp

clean:
	rm -f *.o gddemo
